import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { google, sheets_v4 } from 'googleapis';
import Link from 'next/link';
import Header from './components/Header';

type QueryType = {
  query: {
    id: number;
  };
}

export async function getServerSideProps({ query }: QueryType) {

  const auth = await google.auth.getClient({
    scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly']
  });

  const sheets = google.sheets({
    version: 'v4',
    auth
  });

  const getLastRow = async () => {
    let lastRow = process.env.LAST_ROW;
    const returnValue = lastRow ? lastRow : "6";
    return returnValue;
  }

  const lastRow: string = await getLastRow();

  const range = `VocabularyFlashcardsWordList!A1:A${lastRow}`;

  const getSheetID = async () => {
    let envSheetID = process.env.SHEET_ID;
    const returnValue = envSheetID ? envSheetID : "invalid_sheet_id";
    return returnValue;
  }

  const sheetID: string = await getSheetID();

  const responsePayload: sheets_v4.Params$Resource$Spreadsheets$Values$Get = {
    spreadsheetId: sheetID,
    range,
  }

  const response = await sheets.spreadsheets.values.get(responsePayload);

  const flashcards = response.data.values!.flat();
  console.log(flashcards);

  return {
    props: {
      flashcards,
    },
  };
}

export default function Home({ flashcards }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vocabulary Flashcards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Vocabulary <a href="https://github.com/HarshitDoshi">Flashcardz</a> ⚡
        </h1>

        <p className={styles.description}>
          Tap a card to read more about the word.
        </p>

        <div className={styles.grid}>
          {flashcards.map((v: any, i: any) => (
            <Link key={v} href={`flashcards/${i + 1}`}>
              <div className={styles.card}>
                <h2>{v}</h2>
                <p>{ }</p>
              </div>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by{' '}
        <span>

          <a
            className={styles.shunyaek}
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            shunyaek
          </a>
        </span>
      </footer>
    </div>
  )
}
